task_agent:
    task_type: daily
    store_code: PANDAB2B
    database_name: batch_script_agent
    base_url: http://localhost:60001/
    remote_base_url: ""

sqldump_cfg:
    dump_path: /media/estore/PythonScriptAgent/to_outlet/SQLDUMP_files
    hostname: b2b-mysql01.mysql.database.azure.com
    port: 3306
    username: compare_b2b
    passwd: 3b714043292de9ec909dffac612418b4

zip_cfg:
    zip_store_path: /media/estore/PythonScriptAgent/SQLDUMP_files/compress
    unzip_store_path: /media/estore/PythonScriptAgent/SQLDUMP_files/decompress
  
sftp_cfg:
    hostname: ""
    username: ""
    password: ""
    sftp_remote_path: ""
    port: 22

