mysql:
    hostname: localhost
    username: compare_b2b
    pwd: 3b714043292de9ec909dffac612418b4
    port: 3306
    database_name: ""

pdf:
    store_path: "/media/b2b/rexbridge-b2b.com/uploads/bataras/"





